---
apiVersion: v1
kind: Namespace
metadata:
  name: openldap
  labels:
    app: openldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - image: osixia/openldap:1.5.0
        imagePullPolicy: IfNotPresent
        name: openldap
        ports:
        - containerPort: 636
          name: https
          protocol: TCP
        - containerPort: 389
          name: http
          protocol: TCP
        env:
        - name: LDAP_ORGANISATION
          value: "My Example Organization"
        - name: LDAP_DOMAIN
          value: "example.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "0.5"
            memory: 0.5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
spec:
  ports:
  - name: https
    port: 30636
    protocol: TCP
    targetPort: 636
  - name: http
    port: 30389
    protocol: TCP
    targetPort: 389
  selector:
    app: openldap
  type: LoadBalancer
