---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: test-kc-test-test-kc-test
  name: test-kc-test-test-kc-test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '1Gi'
  storageClassName: 'ca99d7c8-a82e-11eb-a8aa-0e37bd1d541d'
